--- 
abstract: Print like Python.
author: 
  - Ask Solem <asksh@cpan.org>
build_requires: 
  Scalar::Util: 1.14
  Test::Simple: 0.42
distribution_type: module
generated_by: Module::Install version 0.68
license: bsd
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Acme-Locals
no_index: 
  directory: 
    - examples
    - devel
    - inc
    - t
requires: 
  PadWalker: 0
  Params::Util: 0
  perl: 5.6.0
  version: 0
version: 0.0.1
